export const ICON_NAMES = [
  'arrow-back',
  'home-bold',
  'home-fill',
  'settings',
  'bulb',
  'play-arrow-right',
  'play-arrow-left',
  'swap-vert',
  'swap-fill',
  'chat',
  'transfer',
  'electricity-circle',
  'electricity-fill',
  'warning',
  'check-mark',
  'notifications',
  'face-scan',
  'arrow-left',
  'send',
  'box',
  'kebab-menu',
  'phone-bill',
  'mail-checkmark',
  'euros',
  'token-branded',
  'soloar:eye-bold',
  'ri:eye-off',
  'backpack',
  'phantom',
  'trust',
  'zerion',
  'fingerprint',
  'tracking-box',
  'pencil-checkmark',
  'scan',
  'hand-withdraw',
  'star'
] as const

export type IconName = typeof ICON_NAMES[number]

